In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Problem statement

For many ML-models, but not all, it is required that all the input features are numerical - since the values they have are being used in mathematical operations. 
However, in the previous lab with the used cars dataset, we had to omit all features that were not already numerical since we hadn't yet learned how to deal with them.

In this lab, we'll learn of a technique called One Hot Encoding, which is a method of transforming what we call *categorical* features into numerical ones.

**Let's randomly generate a dataset to work with here**

In [2]:
ages = np.random.randint(20, 60, size=10)
genders = np.random.choice(['male', 'female', 'unknown'], size=10)
salaries = np.random.randint(30000, 80000, size=10)

data = {'Age': ages, 'Gender': genders, 'Salary': salaries}
df = pd.DataFrame(data)

df

   Age   Gender  Salary
0   51  unknown   69051
1   31     male   63428
2   31  unknown   30376
3   22   female   34411
4   55  unknown   65664
5   25     male   49842
6   39     male   38880
7   42     male   70528
8   51  unknown   77749
9   21   female   53943

In the dataset above, the column Gender is called *categorical*.

A categorical feature is one in which we can't say that one value is more or less than another one. 

In this case, male is neither more or less than female, i.e., we can't say that male < female or vice-versa.

Some other examples of categorical data are hair color (red, blonde, or black), political affiliation (republican, democrat, or other), and favourite food (sushi, kebab, or vegetables). Again, these are considered categorical because one is not more than the other.

In contrast, the columns Age and Salary are definitely not categorical since you can directly compare them. A salary of 60000 > 30000, and conversely 39 is objectively older than 26.

**One Hot Encoding**

A very simple way of dealing with categorical features is simply to create boolean columns, one for each of the values of our categorical column. This is called one hot encoding. We can do this in several ways, and Pandas has a pretty neat function for it aswell.

In [ ]:
df

In [3]:
# 1. we call on the get_dummies function
# 2. we give it the dataset as the first argument
# 3. We tell it which columns we want to one hot encode

pd.get_dummies(df, columns = ['Gender'])

   Age  Salary  Gender_female  Gender_male  Gender_unknown
0   51   69051          False        False            True
1   31   63428          False         True           False
2   31   30376          False        False            True
3   22   34411           True        False           False
4   55   65664          False        False            True
5   25   49842          False         True           False
6   39   38880          False         True           False
7   42   70528          False         True           False
8   51   77749          False        False            True
9   21   53943           True        False           False

In [ ]:
# 1. we call on the get_dummies function
# 2. we give it the dataset as the first argument
# 3. We tell it which columns we want to one hot encode
# 4. In addition, we also let the function know that we want 1/0 and not True/False

pd.get_dummies(df, columns = ['Gender'], dtype=int)

The result is a new dataframe, with categorical features transformed into numerical ones that we can use for the models that require it! 

If now use these features to try to predict the salary for a given employee, we might have something like this (for a linear model)

$$ salary = w_4 \cdot (Age) + w_3 \cdot (Gender\ female) + w_2 \cdot (Gender\ male) + w_1 \cdot (Gender\ unkown) + w_0 $$

**A word of caution**

However, you must be careful to not fall into the trap of believing that numerical columns can't be categorical! 

Take this for example:

In [4]:
ages = np.random.randint(20, 60, size=10)
genders = np.random.choice(['male', 'female'], size=10)
employee_ids = np.random.randint(10, 20, size=10)
salaries = np.random.randint(30000, 80000, size=10)

data = {'Employee Dept. ID': employee_ids, 'Age': ages, 'Gender': genders, 'Salary': salaries}
df = pd.DataFrame(data)

df

   Employee Dept. ID  Age  Gender  Salary
0                 19   26  female   74266
1                 11   54    male   63616
2                 15   31    male   40680
3                 13   23    male   52742
4                 10   48  female   57745
5                 16   24    male   39681
6                 16   50  female   50603
7                 18   27    male   75828
8                 13   22    male   59677
9                 12   55    male   65497

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee Dept. ID  10 non-null     int32
 1   Age                10 non-null     int32
 2   Gender             10 non-null     str
 3   Salary             10 non-null     int32
dtypes: int32(3), str(1)
memory usage: 332.0 bytes

Obviously, Employee Dept.ID is a numerical column and we can technically do mathematical comparisons between each Employee ID.

19 > 10. Obviously.

However, imagine now using that column, as is, as a feature for, say, a linear model that predicts salary. Then it might look like this:

$$ salary = w_2 \cdot (Employee\ Dept.\ ID) + w_1 \cdot (Age) + w_0 $$

According to this, a higher Employee Dept. ID contributes more to the predicted salary than a lower Employee Dept. ID. That doesn't seem to make any sense at all.

In fact, the column Employee Dept. ID is also a categorical feature, a *numerical categorical* feature. We could technically do comparisons between its values, but we really shouldn't - since it doesnt make sense. 

We can treat numerical categorical columns just like we did with ordinary categorical features - we'll one hot encode them.

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee Dept. ID  10 non-null     int32
 1   Age                10 non-null     int32
 2   Gender             10 non-null     str
 3   Salary             10 non-null     int32
dtypes: int32(3), str(1)
memory usage: 332.0 bytes

In [7]:
pd.get_dummies(df, columns = ['Gender', 'Employee Dept. ID'], dtype=int)  # note that we can one hot encode several columns at the same time

,Age,Salary,Gender_female,Gender_male,Employee Dept. ID_10,Employee Dept. ID_11,Employee Dept. ID_12,Employee Dept. ID_13,Employee Dept. ID_15,Employee Dept. ID_16,Employee Dept. ID_18,Employee Dept. ID_19
0,26,74266,1,0,0,0,0,0,0,0,0,1
1,54,63616,0,1,0,1,0,0,0,0,0,0
2,31,40680,0,1,0,0,0,0,1,0,0,0
3,23,52742,0,1,0,0,0,1,0,0,0,0
4,48,57745,1,0,1,0,0,0,0,0,0,0
5,24,39681,0,1,0,0,0,0,0,1,0,0
6,50,50603,1,0,0,0,0,0,0,1,0,0
7,27,75828,0,1,0,0,0,0,0,0,1,0
8,22,59677,0,1,0,0,0,1,0,0,0,0
9,55,65497,0,1,0,0,1,0,0,0,0,0

För mer information, läs [dokumentationen!](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html)

In [14]:
ages = np.random.randint(20, 60, size=10)
genders = np.random.choice(['male', 'female', 'other'], size=10)
education = np.random.choice(['high school', 'bachelor', 'phd'], size=10)
salaries = np.random.randint(30000, 80000, size=10)

data = {'Age': ages, 'Gender': genders, 'Education': education, 'Salary': salaries}
df = pd.DataFrame(data)



df

   Age  Gender    Education  Salary
0   41   other     bachelor   71471
1   25  female          phd   35487
2   41    male          phd   61286
3   20    male          phd   70456
4   56  female          phd   68862
5   42   other     bachelor   49529
6   44    male     bachelor   39305
7   57  female  high school   67620
8   21   other          phd   33138
9   52    male  high school   32358

In [16]:
def edu_mapper(value):

    if value=='phd':
        return 3
    elif value=='bachelor': 
        return 2
    else:
        return 1

In [18]:
numerical_education = [edu_mapper(level) for level in df['Education']]
numerical_education

[2, 3, 3, 3, 3, 2, 2, 1, 3, 1]

In [19]:
df['New Education'] = numerical_education

In [20]:
df

   Age  Gender    Education  Salary  New Education
0   41   other     bachelor   71471              2
1   25  female          phd   35487              3
2   41    male          phd   61286              3
3   20    male          phd   70456              3
4   56  female          phd   68862              3
5   42   other     bachelor   49529              2
6   44    male     bachelor   39305              2
7   57  female  high school   67620              1
8   21   other          phd   33138              3
9   52    male  high school   32358              1

$$ salary = w_2 \cdot (Age) + w_1 \cdot (New\ Education) + w_0$$

Ni kan göra som ovan, men ni kan också givetvis köra dummy variables ändå.

In [22]:
ages = np.random.randint(20, 60, size=10)
genders = np.random.choice(['male', 'female', 'other'], size=10)
education = np.random.choice(['high school', 'bachelor', 'phd'], size=10)
salaries = np.random.randint(30000, 80000, size=10)

data = {'Age': ages, 'Gender': genders, 'Education': education, 'Salary': salaries}
df = pd.DataFrame(data)


pd.get_dummies(df, columns = ['Education'], dtype=int)  # note that we can one hot encode several columns at the same time

,Age,Gender,Salary,Education_bachelor,Education_high school,Education_phd
0,42,female,61571,0,0,1
1,20,female,78942,0,1,0
2,59,other,42509,0,0,1
3,37,other,35686,1,0,0
4,32,other,64862,0,0,1
5,44,other,71189,0,0,1
6,45,male,73662,0,0,1
7,34,male,44626,0,0,1
8,43,other,47427,0,0,1
9,45,female,32024,0,0,1

$$ salary = w_4 \cdot (Age) + w_3 \cdot (Education\ bachelor) + w_2 \cdot (Education\ high\ school) + w_1 \cdot (Education\ phd) + w_0$$

In [23]:
pd.get_dummies(df, columns = ['Gender', 'Education'], dtype=int)

,Age,Salary,Gender_female,Gender_male,Gender_other,Education_bachelor,Education_high school,Education_phd
0,42,61571,1,0,0,0,0,1
1,20,78942,1,0,0,0,1,0
2,59,42509,0,0,1,0,0,1
3,37,35686,0,0,1,1,0,0
4,32,64862,0,0,1,0,0,1
5,44,71189,0,0,1,0,0,1
6,45,73662,0,1,0,0,0,1
7,34,44626,0,1,0,0,0,1
8,43,47427,0,0,1,0,0,1
9,45,32024,1,0,0,0,0,1

**The curse of dimensionality**

One Hot Encoding is great, but you should be careful using it. If the categorical column you transform has too many values, it will translate to equally many new columns. This means that the dimensionality of your features increases (each feature is one dimension). As you increase the number of features, it also turns out that it gets more and more difficult to fit a model to it - unless you have a big enough data set!

Think about it. If you have a very small data set (10 samples), and 1000 features - you're not going to be able to make any sense of the underlying process you're trying to model.

However, if you have a relatively big data set (1M samples), and 1000 features - you **might** be able to make sense of the underlying process and produce a good model.

**conclusion**

One Hot Encoding is great, use it. But be careful. If the column your transforming has *alot* of possible values (say, perhaps over 20 or 30), it might case issues if you don't also have a correspondingly good amount of data.

Clear warning sign: if the number of features exceed the number of training samples, you're most likely in trouble.

What you want is for your training samples >> number of features

$num samples>> num features$

---

Further efficency improvements.

In [24]:
ages = np.random.randint(20, 60, size=10)
genders = np.random.choice(['male', 'female', 'unknown', 'alien'], size=10)
employee_ids = np.random.randint(10, 20, size=10)
salaries = np.random.randint(30000, 80000, size=10)

data = {'Employee Dept. ID': employee_ids, 'Age': ages, 'Gender': genders, 'Salary': salaries}
df = pd.DataFrame(data)

df

   Employee Dept. ID  Age   Gender  Salary
0                 12   36    alien   44096
1                 14   35    alien   61908
2                 15   37    alien   79173
3                 11   32  unknown   37577
4                 16   30   female   45887
5                 14   31   female   55938
6                 11   41    alien   34095
7                 10   43     male   62366
8                 15   39   female   58418
9                 11   39    alien   39342

In [36]:

#df["Gender"].unique()
pd.get_dummies(df, columns=['Gender'], dtype=int)

,Employee Dept. ID,Age,Salary,Gender_alien,Gender_female,Gender_male,Gender_unknown
0,12,36,44096,1,0,0,0
1,14,35,61908,1,0,0,0
2,15,37,79173,1,0,0,0
3,11,32,37577,0,0,0,1
4,16,30,45887,0,1,0,0
5,14,31,55938,0,1,0,0
6,11,41,34095,1,0,0,0
7,10,43,62366,0,0,1,0
8,15,39,58418,0,1,0,0
9,11,39,39342,1,0,0,0

One strategy to "win" one less column, is to drop one of the resulting one-hot-encoded columns.

In [37]:
pd.get_dummies(df, columns=['Gender'], dtype=int, drop_first=True)

   Employee Dept. ID  Age  Salary  Gender_female  Gender_male  Gender_unknown
0                 12   36   44096              0            0               0
1                 14   35   61908              0            0               0
2                 15   37   79173              0            0               0
3                 11   32   37577              0            0               1
4                 16   30   45887              1            0               0
5                 14   31   55938              1            0               0
6                 11   41   34095              0            0               0
7                 10   43   62366              0            1               0
8                 15   39   58418              1            0               0
9                 11   39   39342              0            0               0

**Another trick is to group categories together**

In [47]:
ages = np.random.randint(20, 60, size=1000)
genders = np.random.choice(['male', 'female'], size=1000)
employee_ids = np.random.randint(10, 50, size=1000)
salaries = np.random.randint(30000, 80000, size=1000)

data = {'Employee Dept. ID': employee_ids, 'Age': ages, 'Gender': genders, 'Salary': salaries}
df = pd.DataFrame(data)

df
new_df= pd.get_dummies(df, columns=["Gender"], dtype=int)
new_df

     Employee Dept. ID  Age  Salary  Gender_female  Gender_male
0                   36   42   72725              1            0
1                   38   35   69995              0            1
2                   47   20   41389              0            1
3                   12   32   38304              1            0
4                   16   38   71459              0            1
..                 ...  ...     ...            ...          ...
995                 11   41   48193              1            0
996                 30   41   33618              1            0
997                 13   30   48130              1            0
998                 18   26   64889              0            1
999                 34   52   67557              1            0

[1000 rows x 5 columns]

In [ ]:
pd.get_dummies(df, columns=['Employee Dept. ID'], dtype=int)

As we can see above, there are simply too many Deptepartment IDs to be one-hot-encoded (they yield 40 new features, which can contribute to the curse of dimensionality significantly). We can group them together into a smaller number of categories, if there is a logic to it.

Assume now, e.g., that 

* Depts 10-19 are "Sales"
* Depts 20-29 are "Marketing"
* Depts 30-39 are "HR"
* Depts 40-49 are "IT"

In [49]:
def group_dept(dept_id):
    if 10 <= dept_id <= 19:
        return 'Sales'
    elif 20 <= dept_id <= 29:
        return 'Marketing'
    elif 30 <= dept_id <= 39:
        return 'HR'
    elif 40 <= dept_id <= 49:
        return 'IT'

In [50]:
new_dept_groupings = [group_dept(dept_id) for dept_id in df['Employee Dept. ID']]


df['Employee Dept. Group'] = new_dept_groupings

In [51]:
df

     Employee Dept. ID  Age  Gender  Salary Employee Dept. Group
0                   36   42  female   72725                   HR
1                   38   35    male   69995                   HR
2                   47   20    male   41389                   IT
3                   12   32  female   38304                Sales
4                   16   38    male   71459                Sales
..                 ...  ...     ...     ...                  ...
995                 11   41  female   48193                Sales
996                 30   41  female   33618                   HR
997                 13   30  female   48130                Sales
998                 18   26    male   64889                Sales
999                 34   52  female   67557                   HR

[1000 rows x 5 columns]

In [68]:
pd.get_dummies(df, columns=['Employee Dept. Group', 'Gender'], dtype=int)

,Employee Dept. ID,Age,Salary,Employee Dept. Group_HR,Employee Dept. Group_IT,Employee Dept. Group_Marketing,Employee Dept. Group_Sales,Gender_female,Gender_male
0,36,42,72725,1,0,0,0,1,0
1,38,35,69995,1,0,0,0,0,1
2,47,20,41389,0,1,0,0,0,1
3,12,32,38304,0,0,0,1,1,0
4,16,38,71459,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...
995,11,41,48193,0,0,0,1,1,0
996,30,41,33618,1,0,0,0,1,0
997,13,30,48130,0,0,0,1,1,0
998,18,26,64889,0,0,0,1,0,1
999,34,52,67557,1,0,0,0,1,0

In [69]:
almost_done_df = pd.get_dummies(df, columns=['Employee Dept. Group', 'Gender'], dtype=int, drop_first=True)

almost_done_df

,Employee Dept. ID,Age,Salary,Employee Dept. Group_IT,Employee Dept. Group_Marketing,Employee Dept. Group_Sales,Gender_male
0,36,42,72725,0,0,0,0
1,38,35,69995,0,0,0,1
2,47,20,41389,1,0,0,1
3,12,32,38304,0,0,1,0
4,16,38,71459,0,0,1,1
...,...,...,...,...,...,...,...
995,11,41,48193,0,0,1,0
996,30,41,33618,0,0,0,0
997,13,30,48130,0,0,1,0
998,18,26,64889,0,0,1,1
999,34,52,67557,0,0,0,0

We can now train on the following features

In [70]:
almost_done_df.columns

Index(['Employee Dept. ID', 'Age', 'Salary', 'Employee Dept. Group_IT',
       'Employee Dept. Group_Marketing', 'Employee Dept. Group_Sales',
       'Gender_male'],
      dtype='str')

In [ ]:
columns_to_keep = ['Age', 'Salary', 'Employee Dept. Group_IT',
       'Employee Dept. Group_Marketing', 'Employee Dept. Group_Sales',
       'Gender_male']

In [ ]:
trainable_df = almost_done_df[columns_to_keep]
trainable_df

JUST FYI, you dont have to DROP FIRST. It's cute, but nowadays not really needed.